version: '2'

networks:
  avnet:

services:
  mongo:
    image: mongo:3.4
    volumes:
      - ./.db:/data/db
    networks:
      - avnet
    ports:
      - "127.0.0.1:27017:27017"
    container_name: mongo
